# Generated by Django 2.2.4 on 2019-08-22 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20190822_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moreinfo',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Mes Informació'),
            preserve_default=False,
        ),
    ]
