# Generated by Django 2.2.4 on 2019-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_auto_20190822_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Desccripció'),
        ),
        migrations.AlterField(
            model_name='project',
            name='moreinfo',
            field=models.CharField(max_length=200, verbose_name='Mes Informació'),
        ),
    ]
