# Generated by Django 2.2.4 on 2019-08-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_auto_20190822_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='moreinfo',
            field=models.URLField(blank=True, null=True, verbose_name='Mes Informació'),
        ),
    ]
